import {
  ANCHOR_NAMES,
  type AnchorName,
  type AnimationDefinition,
  type AnimationId,
  type CanonicalBodyContract,
  type FrameDefinition,
  type Point,
  type PoseChannel,
  type PoseTags,
  type SemanticLayer,
} from './types';

export const DEFAULT_LAYER_ORDER = [
  'groundShadow',
  'tailBack',
  'weaponBack',
  'earBack',
  'tuftBack',
  'rearFoot',
  'rearLeg',
  'rearArm',
  'rearHand',
  'body',
  'topBack',
  'head',
  'face',
  'bottoms',
  'frontLeg',
  'frontFoot',
  'top',
  'frontArm',
  'frontHand',
  'tuftFront',
  'hoodOrHatFront',
  'weaponFront',
  'accessoryFront',
] as const satisfies readonly SemanticLayer[];

const ROOT = Object.freeze({ x: 128, y: 232 });

const BASE_ANCHORS: Readonly<Record<AnchorName, Point>> = Object.freeze({
  root: ROOT,
  ground: { x: 128, y: 232 },
  neck: { x: 128, y: 120 },
  headTop: { x: 128, y: 35 },
  faceCenter: { x: 145, y: 82 },
  shoulderRear: { x: 105, y: 132 },
  elbowRear: { x: 96, y: 157 },
  handRear: { x: 91, y: 183 },
  shoulderFront: { x: 154, y: 135 },
  elbowFront: { x: 165, y: 155 },
  handFront: { x: 174, y: 178 },
  waist: { x: 128, y: 179 },
  hipRear: { x: 116, y: 182 },
  kneeRear: { x: 111, y: 205 },
  footRear: { x: 110, y: 230 },
  hipFront: { x: 141, y: 182 },
  kneeFront: { x: 147, y: 205 },
  footFront: { x: 150, y: 230 },
  tailRoot: { x: 96, y: 174 },
  weaponGrip: { x: 172, y: 177 },
});

const POSE_CHANNELS = [
  'body',
  'head',
  'face',
  'tail',
  'tuft',
  'rearArm',
  'rearHand',
  'frontArm',
  'frontHand',
  'rearLeg',
  'frontLeg',
  'rearFoot',
  'frontFoot',
  'weapon',
] as const satisfies readonly PoseChannel[];

function makePose(
  base: string,
  overrides: Partial<Record<PoseChannel, string>> = {},
): PoseTags {
  return Object.freeze(
    Object.fromEntries(
      POSE_CHANNELS.map((channel) => [channel, overrides[channel] ?? base]),
    ) as Record<PoseChannel, string>,
  );
}

function makeAnchors(
  overrides: Partial<Record<AnchorName, Point>> = {},
): Readonly<Record<AnchorName, Point>> {
  const anchors = {} as Record<AnchorName, Point>;
  for (const name of ANCHOR_NAMES) {
    const value = overrides[name] ?? BASE_ANCHORS[name];
    anchors[name] = Object.freeze({ x: value.x, y: value.y });
  }
  return Object.freeze(anchors);
}

function makeFrame(
  animationId: AnimationId,
  index: number,
  durationTicks: number,
  poseName: string,
  anchorOverrides: Partial<Record<AnchorName, Point>> = {},
  poseOverrides: Partial<Record<PoseChannel, string>> = {},
  layerOrder: readonly SemanticLayer[] = DEFAULT_LAYER_ORDER,
): FrameDefinition {
  return Object.freeze({
    id: `${animationId}_${index}`,
    durationTicks,
    rootOrigin: ROOT,
    groundY: 232,
    anchors: makeAnchors(anchorOverrides),
    layerOrder,
    poses: makePose(poseName, poseOverrides),
  });
}

const idle: AnimationDefinition = Object.freeze({
  id: 'idle',
  loop: true,
  frames: Object.freeze([
    makeFrame('idle', 0, 11, 'idle-settle'),
    makeFrame(
      'idle',
      1,
      10,
      'idle-inhale',
      {
        neck: { x: 128, y: 118 },
        headTop: { x: 128, y: 33 },
        faceCenter: { x: 145, y: 80 },
        shoulderRear: { x: 105, y: 130 },
        elbowRear: { x: 96, y: 155 },
        handRear: { x: 91, y: 181 },
        shoulderFront: { x: 154, y: 133 },
        elbowFront: { x: 165, y: 153 },
        handFront: { x: 174, y: 176 },
        weaponGrip: { x: 172, y: 175 },
      },
      { body: 'idle-expanded', tuft: 'idle-lift' },
    ),
    makeFrame(
      'idle',
      2,
      11,
      'idle-peak',
      {
        neck: { x: 128, y: 117 },
        headTop: { x: 128, y: 32 },
        faceCenter: { x: 145, y: 79 },
        shoulderRear: { x: 105, y: 129 },
        elbowRear: { x: 96, y: 154 },
        handRear: { x: 92, y: 180 },
        shoulderFront: { x: 154, y: 132 },
        elbowFront: { x: 165, y: 152 },
        handFront: { x: 173, y: 175 },
        weaponGrip: { x: 171, y: 174 },
      },
      { body: 'idle-expanded', face: 'blink', tuft: 'idle-lift' },
    ),
    makeFrame(
      'idle',
      3,
      12,
      'idle-exhale',
      {
        neck: { x: 128, y: 119 },
        headTop: { x: 128, y: 34 },
        faceCenter: { x: 145, y: 81 },
        shoulderRear: { x: 105, y: 131 },
        elbowRear: { x: 96, y: 156 },
        handRear: { x: 91, y: 182 },
        shoulderFront: { x: 154, y: 134 },
        elbowFront: { x: 165, y: 154 },
        handFront: { x: 174, y: 177 },
        weaponGrip: { x: 172, y: 176 },
      },
    ),
  ]),
});

const run: AnimationDefinition = Object.freeze({
  id: 'run',
  loop: true,
  frames: Object.freeze([
    makeFrame(
      'run',
      0,
      5,
      'run-contact-a',
      {
        neck: { x: 132, y: 120 },
        headTop: { x: 132, y: 35 },
        faceCenter: { x: 149, y: 82 },
        shoulderRear: { x: 108, y: 132 },
        elbowRear: { x: 124, y: 150 },
        handRear: { x: 142, y: 165 },
        shoulderFront: { x: 157, y: 135 },
        elbowFront: { x: 143, y: 154 },
        handFront: { x: 127, y: 171 },
        waist: { x: 131, y: 179 },
        hipRear: { x: 118, y: 182 },
        kneeRear: { x: 134, y: 201 },
        footRear: { x: 151, y: 230 },
        hipFront: { x: 143, y: 182 },
        kneeFront: { x: 129, y: 207 },
        footFront: { x: 110, y: 230 },
        tailRoot: { x: 99, y: 174 },
        weaponGrip: { x: 128, y: 170 },
      },
      {
        rearArm: 'swing-forward',
        frontArm: 'swing-back',
        rearLeg: 'stride-forward',
        frontLeg: 'stride-back',
        rearFoot: 'contact-forward',
        frontFoot: 'contact-back',
        weapon: 'carry-back',
      },
    ),
    makeFrame(
      'run',
      1,
      5,
      'run-down-a',
      {
        neck: { x: 132, y: 124 },
        headTop: { x: 132, y: 39 },
        faceCenter: { x: 149, y: 86 },
        shoulderRear: { x: 108, y: 136 },
        elbowRear: { x: 121, y: 154 },
        handRear: { x: 136, y: 170 },
        shoulderFront: { x: 157, y: 139 },
        elbowFront: { x: 145, y: 157 },
        handFront: { x: 132, y: 174 },
        waist: { x: 131, y: 183 },
        hipRear: { x: 118, y: 186 },
        kneeRear: { x: 130, y: 207 },
        footRear: { x: 146, y: 230 },
        hipFront: { x: 143, y: 186 },
        kneeFront: { x: 128, y: 211 },
        footFront: { x: 110, y: 230 },
        tailRoot: { x: 99, y: 178 },
        weaponGrip: { x: 133, y: 173 },
      },
      {
        body: 'run-compressed',
        rearArm: 'swing-forward-mid',
        frontArm: 'swing-back-mid',
        rearLeg: 'compressed-forward',
        frontLeg: 'compressed-back',
        rearFoot: 'toe-forward',
        frontFoot: 'planted-back',
        weapon: 'carry-back',
      },
    ),
    makeFrame(
      'run',
      2,
      5,
      'run-passing-a',
      {
        neck: { x: 130, y: 120 },
        headTop: { x: 130, y: 35 },
        faceCenter: { x: 147, y: 82 },
        shoulderRear: { x: 106, y: 132 },
        elbowRear: { x: 108, y: 155 },
        handRear: { x: 109, y: 178 },
        shoulderFront: { x: 155, y: 135 },
        elbowFront: { x: 155, y: 156 },
        handFront: { x: 155, y: 177 },
        waist: { x: 129, y: 179 },
        hipRear: { x: 116, y: 182 },
        kneeRear: { x: 118, y: 204 },
        footRear: { x: 124, y: 228 },
        hipFront: { x: 141, y: 182 },
        kneeFront: { x: 139, y: 205 },
        footFront: { x: 136, y: 230 },
        tailRoot: { x: 97, y: 174 },
        weaponGrip: { x: 157, y: 176 },
      },
      {
        rearArm: 'passing-forward',
        frontArm: 'passing-back',
        rearLeg: 'passing-forward',
        frontLeg: 'passing-back',
        rearFoot: 'passing-forward',
        frontFoot: 'push-off-back',
        weapon: 'carry-back',
      },
    ),
    makeFrame(
      'run',
      3,
      5,
      'run-single-support',
      {
        // Gold run pose: the upper mass leads the root rather than sitting
        // vertically over two planted feet.
        neck: { x: 143, y: 116 },
        headTop: { x: 145, y: 31 },
        faceCenter: { x: 161, y: 78 },
        // Rear arm punches forward while the front arm drives far behind.
        shoulderRear: { x: 115, y: 130 },
        elbowRear: { x: 140, y: 141 },
        handRear: { x: 166, y: 151 },
        shoulderFront: { x: 163, y: 132 },
        elbowFront: { x: 138, y: 145 },
        handFront: { x: 112, y: 158 },
        waist: { x: 132, y: 180 },
        // Front leg is the sole extended support. The rear leg folds up with a
        // 27px foot-height separation, producing readable negative space.
        hipRear: { x: 123, y: 182 },
        kneeRear: { x: 105, y: 197 },
        footRear: { x: 92, y: 203 },
        hipFront: { x: 150, y: 181 },
        kneeFront: { x: 164, y: 203 },
        footFront: { x: 179, y: 230 },
        tailRoot: { x: 103, y: 174 },
        weaponGrip: { x: 112, y: 158 },
      },
      {
        body: 'run-forward-flight',
        head: 'run-forward-focus',
        tail: 'run-lift',
        rearArm: 'swing-forward-strong',
        rearHand: 'swing-forward-open',
        frontArm: 'swing-back-strong',
        frontHand: 'grip-trailing',
        rearLeg: 'flight-bent-back',
        frontLeg: 'support-extended-front',
        rearFoot: 'flight-tucked-back',
        frontFoot: 'support-planted-front',
        weapon: 'run-trail-carry',
      },
    ),
    makeFrame(
      'run',
      4,
      5,
      'run-down-b',
      {
        neck: { x: 132, y: 124 },
        headTop: { x: 132, y: 39 },
        faceCenter: { x: 149, y: 86 },
        shoulderRear: { x: 108, y: 136 },
        elbowRear: { x: 97, y: 155 },
        handRear: { x: 84, y: 172 },
        shoulderFront: { x: 157, y: 139 },
        elbowFront: { x: 170, y: 155 },
        handFront: { x: 185, y: 171 },
        waist: { x: 131, y: 183 },
        hipRear: { x: 118, y: 186 },
        kneeRear: { x: 105, y: 211 },
        footRear: { x: 88, y: 230 },
        hipFront: { x: 143, y: 186 },
        kneeFront: { x: 156, y: 207 },
        footFront: { x: 172, y: 230 },
        tailRoot: { x: 99, y: 178 },
        weaponGrip: { x: 184, y: 170 },
      },
      {
        body: 'run-compressed',
        rearArm: 'swing-back-mid',
        frontArm: 'swing-forward-mid',
        rearLeg: 'compressed-back',
        frontLeg: 'compressed-forward',
        rearFoot: 'planted-back',
        frontFoot: 'toe-forward',
        weapon: 'carry-back',
      },
    ),
    makeFrame(
      'run',
      5,
      5,
      'run-passing-b',
      {
        neck: { x: 130, y: 120 },
        headTop: { x: 130, y: 35 },
        faceCenter: { x: 147, y: 82 },
        shoulderRear: { x: 106, y: 132 },
        elbowRear: { x: 106, y: 155 },
        handRear: { x: 106, y: 177 },
        shoulderFront: { x: 155, y: 135 },
        elbowFront: { x: 157, y: 156 },
        handFront: { x: 159, y: 178 },
        waist: { x: 129, y: 179 },
        hipRear: { x: 116, y: 182 },
        kneeRear: { x: 114, y: 205 },
        footRear: { x: 111, y: 230 },
        hipFront: { x: 141, y: 182 },
        kneeFront: { x: 143, y: 204 },
        footFront: { x: 149, y: 228 },
        tailRoot: { x: 97, y: 174 },
        weaponGrip: { x: 160, y: 177 },
      },
      {
        rearArm: 'passing-back',
        frontArm: 'passing-forward',
        rearLeg: 'passing-back',
        frontLeg: 'passing-forward',
        rearFoot: 'push-off-back',
        frontFoot: 'passing-forward',
        weapon: 'carry-back',
      },
    ),
  ]),
});

const jump: AnimationDefinition = Object.freeze({
  id: 'jump',
  loop: false,
  frames: Object.freeze([
    makeFrame(
      'jump',
      0,
      6,
      'jump-tuck',
      {
        neck: { x: 129, y: 118 },
        headTop: { x: 129, y: 33 },
        faceCenter: { x: 146, y: 80 },
        shoulderRear: { x: 106, y: 130 },
        elbowRear: { x: 94, y: 145 },
        handRear: { x: 104, y: 160 },
        shoulderFront: { x: 155, y: 133 },
        elbowFront: { x: 169, y: 146 },
        handFront: { x: 160, y: 162 },
        waist: { x: 129, y: 177 },
        hipRear: { x: 117, y: 180 },
        kneeRear: { x: 101, y: 195 },
        footRear: { x: 118, y: 207 },
        hipFront: { x: 142, y: 180 },
        kneeFront: { x: 158, y: 195 },
        footFront: { x: 144, y: 210 },
        tailRoot: { x: 97, y: 172 },
        weaponGrip: { x: 159, y: 161 },
      },
      {
        rearArm: 'jump-raised-back',
        frontArm: 'jump-raised-front',
        rearLeg: 'tucked-back',
        frontLeg: 'tucked-front',
        rearFoot: 'tucked-back',
        frontFoot: 'tucked-front',
        weapon: 'carry-back',
      },
    ),
    makeFrame(
      'jump',
      1,
      6,
      'jump-rise',
      {
        neck: { x: 130, y: 116 },
        headTop: { x: 130, y: 31 },
        faceCenter: { x: 147, y: 78 },
        shoulderRear: { x: 107, y: 128 },
        elbowRear: { x: 96, y: 143 },
        handRear: { x: 106, y: 158 },
        shoulderFront: { x: 156, y: 131 },
        elbowFront: { x: 170, y: 144 },
        handFront: { x: 162, y: 160 },
        waist: { x: 130, y: 175 },
        hipRear: { x: 118, y: 178 },
        kneeRear: { x: 113, y: 198 },
        footRear: { x: 111, y: 220 },
        hipFront: { x: 143, y: 178 },
        kneeFront: { x: 149, y: 198 },
        footFront: { x: 152, y: 220 },
        tailRoot: { x: 98, y: 170 },
        weaponGrip: { x: 161, y: 159 },
      },
      {
        rearArm: 'jump-open-back',
        frontArm: 'jump-open-front',
        rearLeg: 'extended-back',
        frontLeg: 'extended-front',
        rearFoot: 'pointed-back',
        frontFoot: 'pointed-front',
        weapon: 'carry-back',
      },
    ),
  ]),
});

const fall: AnimationDefinition = Object.freeze({
  id: 'fall',
  loop: true,
  frames: Object.freeze([
    makeFrame(
      'fall',
      0,
      1,
      'fall-open',
      {
        neck: { x: 128, y: 118 },
        headTop: { x: 128, y: 33 },
        faceCenter: { x: 145, y: 80 },
        shoulderRear: { x: 105, y: 130 },
        elbowRear: { x: 88, y: 142 },
        handRear: { x: 79, y: 160 },
        shoulderFront: { x: 154, y: 133 },
        elbowFront: { x: 173, y: 144 },
        handFront: { x: 183, y: 162 },
        waist: { x: 128, y: 177 },
        hipRear: { x: 116, y: 180 },
        kneeRear: { x: 107, y: 202 },
        footRear: { x: 103, y: 226 },
        hipFront: { x: 141, y: 180 },
        kneeFront: { x: 151, y: 202 },
        footFront: { x: 157, y: 226 },
        tailRoot: { x: 96, y: 172 },
        weaponGrip: { x: 181, y: 161 },
      },
      {
        rearArm: 'fall-open-back',
        frontArm: 'fall-open-front',
        rearLeg: 'fall-open-back',
        frontLeg: 'fall-open-front',
        rearFoot: 'fall-back',
        frontFoot: 'fall-front',
        tuft: 'fall-lift',
        tail: 'fall-lift',
        weapon: 'carry-back',
      },
    ),
  ]),
});

const land: AnimationDefinition = Object.freeze({
  id: 'land',
  loop: false,
  frames: Object.freeze([
    makeFrame(
      'land',
      0,
      4,
      'land-impact',
      {
        neck: { x: 128, y: 128 },
        headTop: { x: 128, y: 43 },
        faceCenter: { x: 145, y: 90 },
        shoulderRear: { x: 103, y: 140 },
        elbowRear: { x: 91, y: 161 },
        handRear: { x: 88, y: 181 },
        shoulderFront: { x: 156, y: 143 },
        elbowFront: { x: 171, y: 161 },
        handFront: { x: 176, y: 181 },
        waist: { x: 128, y: 189 },
        hipRear: { x: 114, y: 192 },
        kneeRear: { x: 98, y: 211 },
        footRear: { x: 91, y: 230 },
        hipFront: { x: 143, y: 192 },
        kneeFront: { x: 160, y: 211 },
        footFront: { x: 169, y: 230 },
        tailRoot: { x: 94, y: 184 },
        weaponGrip: { x: 174, y: 180 },
      },
      {
        body: 'land-squash',
        head: 'land-squash',
        rearArm: 'land-brace-back',
        frontArm: 'land-brace-front',
        rearLeg: 'land-splay-back',
        frontLeg: 'land-splay-front',
        rearFoot: 'land-flat-back',
        frontFoot: 'land-flat-front',
        weapon: 'carry-back',
      },
    ),
    makeFrame(
      'land',
      1,
      7,
      'land-recover',
      {
        neck: { x: 128, y: 123 },
        headTop: { x: 128, y: 38 },
        faceCenter: { x: 145, y: 85 },
        shoulderRear: { x: 104, y: 135 },
        elbowRear: { x: 95, y: 158 },
        handRear: { x: 91, y: 181 },
        shoulderFront: { x: 155, y: 138 },
        elbowFront: { x: 167, y: 157 },
        handFront: { x: 174, y: 179 },
        waist: { x: 128, y: 184 },
        hipRear: { x: 115, y: 187 },
        kneeRear: { x: 108, y: 207 },
        footRear: { x: 105, y: 230 },
        hipFront: { x: 142, y: 187 },
        kneeFront: { x: 151, y: 207 },
        footFront: { x: 156, y: 230 },
        tailRoot: { x: 95, y: 179 },
        weaponGrip: { x: 172, y: 178 },
      },
      {
        body: 'land-rebound',
        rearArm: 'land-recover-back',
        frontArm: 'land-recover-front',
        rearLeg: 'land-recover-back',
        frontLeg: 'land-recover-front',
        rearFoot: 'land-flat-back',
        frontFoot: 'land-flat-front',
        weapon: 'carry-back',
      },
    ),
  ]),
});

const ATTACK_FRONT_ORDER = Object.freeze([
  ...DEFAULT_LAYER_ORDER.filter((layer) => layer !== 'weaponFront'),
  'weaponFront',
] as SemanticLayer[]);

// The strike contact uses a deliberate grip sandwich: the rigid weapon is
// drawn first, then the authored grip paw covers the handle. Other attack
// frames keep the blade above the hand so their wind-up silhouettes stay clear.
const ATTACK_STRIKE_ORDER = Object.freeze(
  DEFAULT_LAYER_ORDER.flatMap<SemanticLayer>((layer) => {
    if (layer === 'weaponFront') return [];
    if (layer === 'frontHand') return ['weaponFront', 'frontHand'];
    return [layer];
  }),
);

const attack: AnimationDefinition = Object.freeze({
  id: 'attack',
  loop: false,
  frames: Object.freeze([
    makeFrame(
      'attack',
      0,
      5,
      'attack-anticipate',
      {
        neck: { x: 121, y: 122 },
        headTop: { x: 121, y: 37 },
        faceCenter: { x: 138, y: 84 },
        shoulderRear: { x: 98, y: 134 },
        elbowRear: { x: 87, y: 153 },
        handRear: { x: 92, y: 170 },
        shoulderFront: { x: 147, y: 137 },
        elbowFront: { x: 139, y: 151 },
        handFront: { x: 126, y: 158 },
        waist: { x: 121, y: 181 },
        hipRear: { x: 108, y: 184 },
        kneeRear: { x: 102, y: 207 },
        footRear: { x: 98, y: 230 },
        hipFront: { x: 134, y: 184 },
        kneeFront: { x: 143, y: 207 },
        footFront: { x: 150, y: 230 },
        tailRoot: { x: 89, y: 176 },
        weaponGrip: { x: 125, y: 157 },
      },
      {
        body: 'attack-lean-back',
        rearArm: 'attack-brace',
        frontArm: 'attack-cocked',
        frontHand: 'grip-cocked',
        rearLeg: 'attack-weighted-back',
        frontLeg: 'attack-light-front',
        weapon: 'attack-cocked-back',
      },
    ),
    makeFrame(
      'attack',
      1,
      4,
      'attack-cock',
      {
        neck: { x: 122, y: 119 },
        headTop: { x: 122, y: 34 },
        faceCenter: { x: 139, y: 81 },
        shoulderRear: { x: 99, y: 131 },
        elbowRear: { x: 90, y: 149 },
        handRear: { x: 98, y: 165 },
        shoulderFront: { x: 148, y: 134 },
        elbowFront: { x: 137, y: 142 },
        handFront: { x: 128, y: 132 },
        waist: { x: 122, y: 178 },
        hipRear: { x: 109, y: 181 },
        kneeRear: { x: 103, y: 205 },
        footRear: { x: 98, y: 230 },
        hipFront: { x: 135, y: 181 },
        kneeFront: { x: 145, y: 205 },
        footFront: { x: 153, y: 230 },
        tailRoot: { x: 90, y: 173 },
        weaponGrip: { x: 128, y: 131 },
      },
      {
        body: 'attack-coil',
        rearArm: 'attack-brace',
        frontArm: 'attack-high-cock',
        frontHand: 'grip-high',
        weapon: 'attack-high-back',
      },
    ),
    makeFrame(
      'attack',
      2,
      3,
      'attack-high-swing',
      {
        neck: { x: 128, y: 116 },
        headTop: { x: 128, y: 31 },
        faceCenter: { x: 145, y: 78 },
        shoulderRear: { x: 105, y: 128 },
        elbowRear: { x: 96, y: 148 },
        handRear: { x: 106, y: 166 },
        shoulderFront: { x: 154, y: 131 },
        elbowFront: { x: 164, y: 119 },
        handFront: { x: 172, y: 104 },
        waist: { x: 128, y: 175 },
        hipRear: { x: 115, y: 178 },
        kneeRear: { x: 107, y: 203 },
        footRear: { x: 101, y: 230 },
        hipFront: { x: 141, y: 178 },
        kneeFront: { x: 151, y: 203 },
        footFront: { x: 159, y: 230 },
        tailRoot: { x: 96, y: 170 },
        weaponGrip: { x: 172, y: 103 },
      },
      {
        body: 'attack-uncoil',
        frontArm: 'attack-high-swing',
        frontHand: 'grip-high-swing',
        weapon: 'attack-high-transition',
      },
      ATTACK_FRONT_ORDER,
    ),
    makeFrame(
      'attack',
      3,
      4,
      'attack-strike',
      {
        // Upper body commits forward while the root remains fixed. The neck is
        // eighteen pixels ahead of the waist, so outfit contours visibly lean rather
        // than translating as a rigid stack.
        neck: { x: 153, y: 114 },
        headTop: { x: 155, y: 29 },
        faceCenter: { x: 172, y: 76 },
        // The free arm throws hard behind the body as a counterweight.
        shoulderRear: { x: 117, y: 130 },
        elbowRear: { x: 94, y: 142 },
        handRear: { x: 73, y: 138 },
        // The weapon arm is compact and driving, avoiding a long tangled chain
        // of sleeve, paw, guard, and blade.
        shoulderFront: { x: 160, y: 130 },
        elbowFront: { x: 174, y: 136 },
        handFront: { x: 185, y: 147 },
        waist: { x: 135, y: 182 },
        // Wide planted stance: rear foot trails, front foot catches the lunge.
        hipRear: { x: 120, y: 185 },
        kneeRear: { x: 105, y: 201 },
        footRear: { x: 91, y: 230 },
        hipFront: { x: 149, y: 183 },
        kneeFront: { x: 162, y: 204 },
        footFront: { x: 176, y: 230 },
        tailRoot: { x: 102, y: 175 },
        weaponGrip: { x: 185, y: 147 },
      },
      {
        body: 'attack-lunge',
        head: 'attack-forward-focus',
        face: 'attack-focus',
        rearArm: 'attack-counterbalance',
        rearHand: 'attack-open-counter',
        frontArm: 'attack-strike',
        frontHand: 'grip-strike',
        rearLeg: 'attack-drive-back',
        frontLeg: 'attack-brace-front',
        rearFoot: 'attack-back-flat',
        frontFoot: 'attack-front-flat',
        weapon: 'attack-strike-front',
      },
      ATTACK_STRIKE_ORDER,
    ),
    makeFrame(
      'attack',
      4,
      6,
      'attack-follow-through',
      {
        neck: { x: 140, y: 124 },
        headTop: { x: 140, y: 39 },
        faceCenter: { x: 157, y: 86 },
        shoulderRear: { x: 117, y: 136 },
        elbowRear: { x: 130, y: 153 },
        handRear: { x: 146, y: 166 },
        shoulderFront: { x: 166, y: 139 },
        elbowFront: { x: 180, y: 158 },
        handFront: { x: 190, y: 178 },
        waist: { x: 140, y: 183 },
        hipRear: { x: 127, y: 186 },
        kneeRear: { x: 114, y: 207 },
        footRear: { x: 104, y: 230 },
        hipFront: { x: 153, y: 186 },
        kneeFront: { x: 164, y: 207 },
        footFront: { x: 174, y: 230 },
        tailRoot: { x: 108, y: 178 },
        weaponGrip: { x: 190, y: 177 },
      },
      {
        body: 'attack-follow-through',
        rearArm: 'attack-counterbalance',
        frontArm: 'attack-follow-through',
        frontHand: 'grip-follow-through',
        weapon: 'attack-low-front',
      },
      ATTACK_FRONT_ORDER,
    ),
    makeFrame(
      'attack',
      5,
      7,
      'attack-recover',
      {
        neck: { x: 133, y: 122 },
        headTop: { x: 133, y: 37 },
        faceCenter: { x: 150, y: 84 },
        shoulderRear: { x: 110, y: 134 },
        elbowRear: { x: 104, y: 156 },
        handRear: { x: 104, y: 179 },
        shoulderFront: { x: 159, y: 137 },
        elbowFront: { x: 169, y: 158 },
        handFront: { x: 176, y: 180 },
        waist: { x: 133, y: 181 },
        hipRear: { x: 120, y: 184 },
        kneeRear: { x: 113, y: 207 },
        footRear: { x: 108, y: 230 },
        hipFront: { x: 146, y: 184 },
        kneeFront: { x: 154, y: 207 },
        footFront: { x: 160, y: 230 },
        tailRoot: { x: 101, y: 176 },
        weaponGrip: { x: 175, y: 179 },
      },
      {
        body: 'attack-recover',
        rearArm: 'attack-recover-back',
        frontArm: 'attack-recover-front',
        frontHand: 'grip-recover',
        weapon: 'carry-back',
      },
    ),
  ]),
});

export const CANONICAL_BODY: CanonicalBodyContract = Object.freeze({
  version: 1,
  logicalWidth: 256,
  logicalHeight: 256,
  tickRate: 60,
  rootOrigin: ROOT,
  groundY: 232,
  unarmedEnvelope: Object.freeze({ x: 67, y: 30, width: 123, height: 202 }),
  weaponEnvelope: Object.freeze({ x: 8, y: 8, width: 240, height: 236 }),
  requiredAnchors: ANCHOR_NAMES,
  defaultLayerOrder: DEFAULT_LAYER_ORDER,
  animations: Object.freeze({ idle, run, jump, fall, land, attack }),
});

export function getAnimation(animationId: AnimationId): AnimationDefinition {
  return CANONICAL_BODY.animations[animationId];
}

export function getFrame(
  animationId: AnimationId,
  frameIndex: number,
): FrameDefinition {
  const frames = getAnimation(animationId).frames;
  if (!Number.isInteger(frameIndex) || frameIndex < 0 || frameIndex >= frames.length) {
    throw new RangeError(
      `Frame index ${frameIndex} is outside ${animationId} coverage (0-${frames.length - 1})`,
    );
  }
  return frames[frameIndex]!;
}

export function totalAnimationTicks(animationId: AnimationId): number {
  return getAnimation(animationId).frames.reduce(
    (sum, frame) => sum + frame.durationTicks,
    0,
  );
}
